In [1]:
from __future__ import print_function
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [2]:
from trackml.dataset import load_event
from trackml.randomize import shuffle_hits
from trackml.score import score_event

In [3]:
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
import seaborn as sns
%matplotlib inline

In [4]:
import os
import numpy as np
import pandas as pd
import glob
import math

In [5]:
from utils import make_uID
det = pd.read_csv('input/detectors.csv')
det.head()
hits_pd = make_uID(det)
hits_pd.shape

(18728, 4)

### load one event

In [6]:
event_prefix = 'event000001000'
hits, cells, particles, truth = load_event(os.path.join('input/train_1', event_prefix))

In [7]:
hits_with_uID = pd.merge(hits, hits_pd, on=['volume_id', 'layer_id', 'module_id'])
from utils import get_features
hits_final = get_features(hits_with_uID)
hits_final.head()

hit_id          x         y       z  volume_id  layer_id  module_id  uID  \
0       1 -64.409897 -7.163700 -1502.5          7         2          1    0   
1       2 -55.336102  0.635342 -1502.5          7         2          1    0   
2       3 -83.830498 -1.143010 -1502.5          7         2          1    0   
3       4 -96.109100 -8.241030 -1502.5          7         2          1    0   
4       5 -62.673599 -9.371200 -1502.5          7         2          1    0   

         x2        y2         z2         r2            r       eta       phi  \
0 -0.042829 -0.004763 -23.184208  64.807045  1503.896973 -3.837108 -3.030827   
1 -0.036804  0.000423 -27.150467  55.339748  1503.518799 -3.994889  3.130112   
2 -0.055707 -0.000760 -17.921406  83.838287  1504.837158 -3.579932 -3.127959   
3 -0.063835 -0.005474 -15.576118  96.461777  1505.593262 -3.439919 -3.056055   
4 -0.041676 -0.006232 -23.709833  63.370335  1503.835815 -3.859459 -2.993168   

     absZ  
0  1502.5  
1  1502.5  
2  1502.5  
3  1502.5  
4  1502.5

In [8]:
filtered_truth = truth[ (truth['weight'] > 5e-7 ) & (truth['particle_id'] != 0) ]
training = hits_final.merge(filtered_truth, on='hit_id')[['uID', 'particle_id']]

In [9]:
truth_particles = pd.Series(np.unique(training['particle_id']))
print("total particles:", truth_particles.shape[0])

total particles: 9292


### Try the RNN model

In [25]:
class HitPredictor(nn.Module):
    def __init__(self, input_dim=20, hidden_dim=20, output_dim=20,
                n_lstm_layers=1):
        super(HitPredictor, self).__init__()
        
        self.hidden_dim = hidden_dim
        self.batch_size = 1
        
        self.lstm = nn.LSTM(input_dim, hidden_dim, n_lstm_layers)
        self.fc = nn.Linear(hidden_dim, output_dim)
        self.hidden = self.init_hidden()
        self.softmax = nn.LogSoftmax(dim=1)

    def init_hidden(self):
        return (torch.zeros(self.lstm.num_layers, self.batch_size, self.hidden_dim),
                torch.zeros(self.lstm.num_layers, self.batch_size, self.hidden_dim))
        
    def forward(self, x):
        input_size = x.size()
        output, self.hidden = self.lstm(x, self.hidden)
        output = self.fc(output.view(len(x), -1))
        tag_scores = self.softmax(output)
        return tag_scores

In [11]:
total_modules = 18728

In [28]:
def inputHits(series):
    tensor = torch.zeros(len(series), 1, total_modules+1)
    for idx, h in enumerate(series):
        tensor[idx][0][h] = 1

    return tensor

In [13]:
def targetHits(series):
    module_idx = series[1:].tolist()
    module_idx.append(total_modules)
    # module_idx += [total_modules]*(21 - len(series))
    return torch.LongTensor(module_idx)

In [14]:
def randomTrack():
    pID = truth_particles.sample(1).values
    hit_series = training[training['particle_id'] == pID[0]]['uID'].values
    input_tensor = inputHits(hit_series)
    target_tensor = targetHits(hit_series)
    return input_tensor, target_tensor

In [15]:
def getInputTarget(hit_series):
    input_tensor = inputHits(hit_series)
    target_tensor = targetHits(hit_series)
    return input_tensor, target_tensor

In [29]:
input_, target_ = randomTrack()
print(input_.size())
print(target_.size())

torch.Size([10, 1, 18729])
torch.Size([10])


In [31]:
def train(input_tensor, target_tensor):

        
    return tag_scores, loss.item()/input_tensor.size(0)

In [18]:
import time
import math

def timeSince(since):
    now = time.time()
    s = now - since
    m = math.floor(s / 60)
    s -= m * 60
    return '%dm %ds' % (m, s)

In [38]:
def check_result(input_, tags_, target_):
    with torch.no_grad():
        print("inputs:", torch.reshape(torch.argmax(input_, dim=2), (-1,)))
        print("predictions:", torch.argmax(tags_, dim=1))
        print("target:", target_)

### Train RNN with all tracks in this event

In [39]:
iter_ = -1
print_every = 200
plot_every = 200
all_losses = []
total_loss = 0
start = time.time()
n_iters = truth_particles.shape[0]

criterion = nn.NLLLoss()
rnn = HitPredictor(input_dim=total_modules+1, hidden_dim=1024, 
                   output_dim=total_modules+1,
                   n_lstm_layers=2)
optimizer = optim.SGD(rnn.parameters(), lr=0.01)

for pID in truth_particles.values:
    iter_ += 1
    
    # prepare the inputs
    input_, target_ = getInputTarget(training[training['particle_id'] == pID]['uID'].values)
    
    # training
    rnn.zero_grad()
    rnn.hidden = rnn.init_hidden()
    tag_scores = rnn(input_)
    
    loss = criterion(tag_scores, target_)
    loss.backward()
    optimizer.step()
    
    total_loss += loss
    if iter_ % print_every == 0:
        print('%s (%d %d%%) %.4f' % (timeSince(start), iter_, iter_ / n_iters * 100, loss))
        check_result(input_, tag_scores, target_)
        
    if iter_ % plot_every == 0:
        all_losses.append(total_loss / plot_every)
        total_loss = 0

print("I am done")

0m 5s (0 0%) 9.8269
inputs: tensor([   864,   1197,   1729,   2608,   5376,   6358,   7652,  15401])
predictions: tensor([  1927,   1927,  18359,  18359,  18359,   3800,   3800,   3800])
target: tensor([  1197,   1729,   2608,   5376,   6358,   7652,  15401,  18728])


KeyboardInterrupt: 

In [29]:
torch.save(rnn.state_dict(), "trained_1event_rnn_model")

In [65]:
with torch.no_grad():
    inputs, target = randomTrack()
    print("inputs:", torch.reshape(torch.argmax(inputs, dim=2), (-1,)))
    print("predictions:", torch.argmax(rnn(inputs), dim=1))
    print("target:", target)

inputs: tensor([   883,   1267,   1948,   1999,   3014,   5624,   6816,   6817,
          8602,  10826,  18340,  18341,  18342,  18728,  18728,  18728,
         18728,  18728,  18728,  18728])
predictions: tensor([ 18728,  18728,  18728,  18728,  18728,  18728,  18728,  18728,
         18728,  18728,  18728,  18728,  18728,  18728,  18728,  18728,
         18728,  18728,  18728,  18728])
target: tensor([  1267,   1948,   1999,   3014,   5624,   6816,   6817,   8602,
         10826,  18340,  18341,  18342,  18728,  18728,  18728,  18728,
         18728,  18728,  18728,  18728])


In [49]:
with torch.no_grad():
    print(torch.argmax(tag_score, dim=1))

tensor([ 18728,  18728,  18728,  18728,  18728,  18728,  18728,  18728,
         18728,  18728,  18728,  18728,  18728,  18728,  18728,  18728,
         18728,  18728,  18728,  18728])
tensor(-0.3111)


tensor([  1345,   3292,   3400,   3508,  10884,  11054,  11221,  11389,
         11559,  11729,  18728,  18728,  18728,  18728,  18728,  18728,
         18728,  18728,  18728,  18728])
[18728, 18728, 18728, 18728, 18728, 18728, 18728, 18728, 18728, 18728, 18728, 18728, 18728, 18728, 18728, 18728, 18728, 18728, 18728, 18728]


In [ ]:
input_, target = randomTrack()
rnn = HitPredictor(input_dim=total_modules+1, hidden_dim=512, output_dim=total_modules+1)
n_iters = 100
print_every = 10
all_losses = []
total_loss = 0

#target.unsqueeze_(-1)
rnn.hidden = rnn.init_hidden()

rnn.zero_grad()
loss = 0
criterion = nn.NLLLoss()

print("input size:", input_.size())
print('target size:', target.size())
output = rnn(input_)
print("output size:", output.size())
print(target)
loss = criterion(output, target)
print(loss)

In [74]:
res = rnn(hot_input)
print(res.size())

torch.Size([1, 20, 18729])
torch.Size([1, 20, 18728])


In [51]:
rnn(input_)

tensor([[[-0.2853, -0.0836,  0.0032, -0.0961, -0.1638,  0.6755, -0.3658,
          -0.3209, -0.2301, -0.2167, -0.0472, -0.0101,  0.4503, -0.1320,
           0.6008,  0.6543, -0.3943,  0.1434,  0.3538, -0.1229]]])

In [53]:
rnn(input_).size()

torch.Size([1, 1, 20])

In [36]:
rnn2 = nn.LSTM(10, 20, 2)
input = torch.randn(4, 1, 10)
print(input.size())
print(input.type())
print(input.dtype)
h0 = torch.randn(2, 1, 20)
c0 = torch.randn(2, 1, 20)
output, hn = rnn2(input, (h0, c0))
print(output)
print(output.size())
print(hn)
print(hn[0].size())

torch.Size([4, 1, 10])
torch.FloatTensor
torch.float32
tensor([[[-0.4815, -0.0463,  0.1335, -0.4550,  0.0416,  0.0668, -0.2156,
           0.1795, -0.1985,  0.3468, -0.0671, -0.0654, -0.3132,  0.4259,
          -0.1269,  0.1254, -0.2169, -0.0644,  0.2965,  0.2403]],

        [[-0.3084, -0.0169,  0.1645, -0.3361, -0.0273,  0.0925, -0.1467,
           0.0871, -0.0591,  0.0959, -0.0969,  0.0291, -0.0683,  0.1409,
          -0.0133,  0.1302, -0.1892,  0.0615,  0.2086, -0.0090]],

        [[-0.1608,  0.0229,  0.0584, -0.2268, -0.0719,  0.1020, -0.1195,
           0.0286,  0.0039,  0.0442, -0.0687,  0.0707,  0.1010,  0.0337,
           0.0333,  0.0966, -0.1918,  0.1150,  0.1390, -0.0721]],

        [[-0.0630,  0.0163,  0.0099, -0.1594, -0.1121,  0.0879, -0.1097,
           0.0414,  0.0447,  0.0109, -0.0768,  0.0672,  0.1772, -0.0198,
           0.0446,  0.0746, -0.1730,  0.0992,  0.0717, -0.1227]]])
torch.Size([4, 1, 20])
(tensor([[[-0.1994, -0.2551, -0.0987,  0.0647,  0.0333, -0.2465,  0.13

In [163]:
m = nn.LogSoftmax(dim=1)

In [164]:
loss = nn.NLLLoss()

In [165]:
input = torch.randn(3, 5, requires_grad=True)

In [166]:
target = torch.tensor([1, 0, 4])
print(target.size())

torch.Size([3])


In [167]:
print(m(input).size())
output = loss(m(input), target)

torch.Size([3, 5])


In [168]:
print(output)

tensor(1.3159)
